### ISSUE TITLE
can't import flask_influxdb

### ISSUE THREAD

**Issue by miettal** [btashton/flask-influxdb#11]
today I tried to update flask-influxdb to 0.3 by pip command.
the installing was success, but importing is failed. (below error)

    from flask_influxdb import InfluxDB
    ModuleNotFoundError: No module named 'flask_influxdb'

I checked site-packages directory, there is no flask-influxdb library directorie.

I think this is caused by the mistake of setup.py

currently, the module name "flask_influxdb" is specified by "py_modules" keyword arguments in setup.py.

    py_modules=["flask_influxdb"],

probably, you should specify "packages" keyword arguments

    packages=["flask_influxdb"],

**Comment by btashton** [comment]
@miettal I apologize for that.  The tests install via setup.py, but they did not use the bdist package.  I will resolve this now.

**Comment by btashton** [comment]
Please see version 0.3.1 that I have published.  I verified the contents of the package on pypi and it looks correct.  https://pypi.org/project/Flask-InfluxDB/0.3.1/

**Comment by miettal** [comment]
thank you!

I confirmed woking your library in my environment!
