### ISSUE TITLE
Unable to pass bind_params to InfluxDBClient

### ISSUE THREAD

**Issue by proffalken** [btashton/flask-influxdb#12]
Hello,

I've got a flask app that instantiates a copy of flask-influxdb as part of a factory.

I then update this factory to talk to the appropriate database depending on data passed to the app via a query string, and then run a query based on other parameters.

In order to follow best practice, I use the `bind_params` variable that is part of InfluxDBClient as follows:
```
influx_query = """
        SELECT last("value") FROM "%s" WHERE ("device_name" = $device_name) AND time >= now() - 1h GROUP BY time(2m) fill(previous)
        """ % measurement_name
                bind_params = { 
                        "device_name": device_name
                        } 
                idbres = self.idb.query(influx_query, bind_params=bind_params)
```
however this results in an error:

```
    idbres = self.idb.query(influx_query, bind_params=bind_params)
TypeError: query() got an unexpected keyword argument 'bind_params'
```

https://github.com/btashton/flask-influxdb/blob/master/flask_influxdb/flask_influxdb.py#L104-L106 and the docs suggest that the call to `query` is is straight passthrough, however something is clearly going awry somewhere!

**Comment by miettal** [comment]
flask-influxdb is using influxdb-python 5.2.2. https://github.com/btashton/flask-influxdb/blob/master/requirements.txt
But bind_params was appared from influxdb-python 5.2.3 probably. https://github.com/influxdata/influxdb-python/pull/678

(by the way, there are unnecessary dependencies and strict version specified dependencies in requirements.txt. I think this is being cause of difficulty to integrate application/library...)

**Comment by btashton** [comment]
You are correct it looks like the InfluxDB client version got pinned to an exact version which it should not have been, but that is really just an issue with setup.py. requirements.txt should just be an issue if you are developing on this library itself. Personally I don't use requirements.txt for true libraries, only applications.

**Comment by miettal** [comment]
sorry my misunderstanding.
Thank you quick-response!

**Comment by btashton** [comment]
I'll update the version pinning to be more flexible. Looks like it should be compatible with the 5.3 series as well.

**Comment by tgree** [comment]
@btashton please update the pinning so that we can use the 5.3 series with flask-influxdb.  It looks like it is still pinned at 5.2.2 and bind_params is unsupported.  Thanks for your hard work!

**Comment by btashton** [comment]
@tgree thanks for pinging me.  I had forgotten about this, it is a simple fix so I'll do it in a few hours and release.

**Comment by btashton** [comment]
@tgree the 0.3.2 version with this fix is up here https://pypi.org/project/Flask-InfluxDB/0.3.2/  I did not test any of the new features feel free to submit a PR for to extend the test suite, but I did test the existing functionality with the 5.3.0 client.

**Comment by tgree** [comment]
Thanks so much for making the update; bind_params seems to be working great for us now!
