### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by brmzkw** [btashton/flask-influxdb#14]
Hey,

With https://github.com/btashton/flask-influxdb/commit/d19cc9677e570969b8cab73c0dd03ebeb3959c70 you added the flag `INFLUXDB_CREATE_DATABASE`. Can you make a new release on pip so we can use this flag?

**Comment by btashton** [comment]
I can create a release this evening and will  update this issue. Thanks for the reminder.

**Comment by btashton** [comment]
@brmzkw version 0.3.3 is now signed and released https://pypi.org/project/Flask-InfluxDB/0.3.3/

**Comment by brmzkw** [comment]
Thanks ❤️
