### ISSUE TITLE
Default of INFLUXDB_UDP_PORT 4444 Conflicts with default INFLUXDB_USE_UDP False

### ISSUE THREAD

**Issue by louspringer** [btashton/flask-influxdb#4]
The client will attempt to use UDP for the client.write_points() call even if INFLUXDB_USE_UDP is set to False. Setting INFLUXDB_UDP_PORT to None is the required default. The client.write_points() fails silently (returns true) if the UDP port is not open to InfluxDB. 

You can test by using the docker image https://hub.docker.com/_/influxdb/ without mapping the UDP port.

**Comment by louspringer** [comment]
See pull request with patch https://github.com/btashton/flask-influxdb/pull/5

I really think this is an upstream bug in influxdata/influxdb-python, since having specified INFLUXDB_USE_UDP False you wouldn't expect it to attempt UDP at all. I'm looking at the upstream https://github.com/influxdata/influxdb-python to see if I can suggest a modification to write_points() that behaves as expected.

**Comment by louspringer** [comment]
Looking at the some more, I'm unable to replicate the issue.

**Comment by btashton** [comment]
@louspringer Let me know if you if you have any more issues.  I am planning on cutting a much needed release to pypi this weekend.
