### ISSUE TITLE
Unable to create DB

### ISSUE THREAD

**Issue by zafstojano** [btashton/flask-influxdb#7]
Hello,

I cloned the project and ran the example.py project, and when I go to localhost:5000/newdb/testdb I get the following error:
`requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22testdb%22 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B344F9A3C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))`

What is the problem for this?
note: I tried disabling the firewall, error still occured.

**Comment by btashton** [comment]
This is resolved in the latest release.
