### ISSUE TITLE
Unable to install sudo  pip3 install Flask-Influx

### ISSUE THREAD

**Issue by girishsukukumar** [btashton/flask-influxdb#9]
Hi 
I am trying to install  Flask-Influx using the command sudo  pip3 install Flask-Influx
 I am getting an error message- Can you help me to understand what is going wrong here ?
pi@vayu:~ $ sudo  pip3 install Flask-Influx
Collecting Flask-Influx
### No matching distribution found for Flask-Influx

The following command show the version of Influx DB I am using. 
pi@vayu:~ $ curl -sL -I localhost:8086/ping
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 2772b613-8399-11e9-96f4-b827eb04bb6b
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.7.4
X-Request-Id: 2772b613-8399-11e9-96f4-b827eb04bb6b
Date: Fri, 31 May 2019 11:42:22 GMT

Regards
Girish

**Comment by btashton** [comment]
@girishsukukumar There is a PR that will be bringing this more in line with the new Influx client.  I should be looking at it and hopefully doing a release this week.

**Comment by btashton** [comment]
@girishsukukumar This is resolved in the latest release.  CI is also now running against the latest InfluxDB.
